name: build

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - 3.2.1
          - 3.1.2
          - 3.0.0
          - 2.7.2
          - 2.6.6
          - 2.5.8
          - 2.4.10
          - 2.3.8
          - 2.2.10
          - jruby-9.4.3.0
          - jruby-9.2.14.0
          - truffleruby-23.0.0
          - truffleruby-22.1.0
        rack-version:
          - # default Rack version

        include:
          - ruby-version: 2.7.2
            rack-version: ~>1.2.0
          - ruby-version: 2.7.2
            rack-version: ~>1.2
          - ruby-version: 2.7.2
            rack-version: ~>2.0.0
          - ruby-version: 2.7.2
            rack-version: ~>2.0

          - ruby-version: 3.2.1
            rack-version: ~>1.2.0
          - ruby-version: 3.2.1
            rack-version: ~>1.2
          - ruby-version: 3.2.1
            rack-version: ~>2.0.0
          - ruby-version: 3.2.1
            rack-version: ~>2.0

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Specify "rack" gem version ${{ matrix.rack-version }}
        if: ${{ matrix.rack-version }}
        run: bundle add rack --version="${{ matrix.rack-version }}"

      - name: Run tests
        run: bundle exec rspec --format documentation
